### ISSUE TITLE
Consider using Rust for improved performance

### ISSUE THREAD

**Issue by Exponential-Workload** [GeopJr/BLAHAJ#14]
I threw together a [quick single-threaded rust implementation](https://codeberg.org/Expo/baaj) of this, and found a ~5.21x performance improvement compared to the multi-threaded implementation of BLAHAJ.
[![Benchmark Results](https://codeberg.org/Expo/baaj/raw/branch/senpai/benchmark.png)](https://codeberg.org/Expo/baaj#performance)

This performance improvement still carries over to larger inputs:
![Another benchmark](https://github.com/GeopJr/BLAHAJ/assets/90570076/2571477d-4860-41ed-82d3-0e6cf5c84039)

For abnormally large files that you usually wouldn't pass through this (32768 lines in the 1st below example, 12MB of `#\n` repeating in the 2nd), the gap does get significantly smaller, however there is still a significant performance improvement:
![3rd benchmark](https://github.com/GeopJr/BLAHAJ/assets/90570076/a4fc53ac-a498-4841-b18e-3db3f267cd7f)
![4th benchmark](https://github.com/GeopJr/BLAHAJ/assets/90570076/0001f488-9ba4-4a19-9ece-bdfb34bc5a9e)
Also, my testing does not include a multithreaded rust implementation, which could be even faster. I'm guessing the lower gap in the last 2 is primarily due to my implementation being singlethreaded.

As a result of this discovery, I thought it might be worth mentioning that rewriting this in rust may provide a significant performance advantage overall :)

Note that my implementation is very barebones, and a more complete implementation may see less of a performance improvement - however it should still see *some* of the 1.3x to 5x improvement.

**Comment by GeopJr** [comment]
Without trying to discourage you, I need you to understand that opening issues like this only makes people avoid the rust community.

This could have been a blog post instead but sure:
- Rust vs Crystal vs C/C++
- Speed vs features vs dev friendliness

# Rust vs Crystal vs C/C++

When does it make sense to "rewrite something in Rust"? I'd say when memory safety and significant performance is lacking.

Crystal and Rust are similar in that regard. They are both LLVM frontends that offer memory safety among other features. The main difference runtime-wise being that Crystal depends on a garbage collector while Rust on a borrow checker.

"Rewrite to Rust" movement makes sense on C/C++ codebases that can suffer from memory safety issues (Linux, fish-shell, curl etc) or interpreted languages like js, python, ruby etc. Not so much here however.

# Speed vs features vs dev friendliness

Earlier versions of this tool worked mostly using macros. I never benchmarked it but it was probably faster than the current higher-level abstractions. Why did it change? Because it was a mess to maintain. It would probably take even Crystal seniors some time to grasp how it worked.

Crystal's standard library is a lot richer than Rust's, providing among other things, a YAML parser, a Colorizer module and a CLI OptionParser. Could performance be improved if I moved away from these? Probably! But also don't want to spend my limited free time writing Colorizers that take care of weird terminal setups and features or OptionParsers that can correctly parse subcommands, arguments, short & long form args etc. I could also have embeded all the flags into a crystal namedtuple and enjoy enough performance improvements just by that alone at the cost of user unfriendliness when adding new flags :shrug:

Also, do I really have to point out that the whole comparison and request is based on a non-feature-complete implementation and minimal cost?

<hr />

Once again, please don't take this the wrong way, rewriting projects in your favorite language with different goals than the original is awesome, I've done it too with projects like https://github.com/GeopJr/pog, but can you imagine if I opened an issue asking the original project to be rewritten in Crystal? Everyone would appreciate it a million times more if those efforts were spent improving the original project, if it was such a big issue to need a rewrite for, especially if it's solvable. 

Even without changing a single line of code and just disabling the garbage collector, has an increase but honestly it's not worth it. (first is with gc disabled, second is latest release)

```
hyperfine --warmup 16 "./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE" "./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE"
Benchmark 1: ./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE
  Time (mean ± σ):      17.3 ms ±   3.5 ms    [User: 7.5 ms, System: 9.8 ms]
  Range (min … max):    12.1 ms …  30.7 ms    150 runs
 
Benchmark 2: ./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE
  Time (mean ± σ):      30.9 ms ±   2.4 ms    [User: 11.8 ms, System: 22.5 ms]
  Range (min … max):    25.7 ms …  35.7 ms    85 runs
 
Summary
  ./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE;./bin/blahaj LICENSE ran
    1.78 ± 0.39 times faster than ./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE;./blahaj LICENSE
```

(FWIW, multithreaded mode doesn't matter anymore and it's likely to cause more issues than it solves, it did matter at some point but single threaded caught up)

On the other hand, I always wanted to make BLAHAJ read colors from a file at runtime, which can be easily done in like 5 lines with the way it works but kept forgetting about it. I gave it a try now - at almost no additional performance and developing cost it can now accept files at runtime and parse them #15
